export const RoutePaths = {
  Home: "/",
  Documents: "/documents",
  DocumentsAdmin: "/documentsAdmin",
  Login: "/login",
  Dashboard: "/dashboard",
  Profile: "/profile",
  Settings: "/settings",
  Portfolio: "/portfolio",
  PortfolioItem: "/portfolio/:id",
  Quotes: "/quotes",
  QuotesItem: "/quotes/:id",
  Marketing: "/marketing",
  FaqAdmin: "/faqAdmin",
  NotificationsAdmin: "/notificationsAdmin",
  ErrorLogging: "/errorLogging",
  UserManagement: "/userManagement",
  NewsAdmin: "/newsAdmin",
} as const;
